### ISSUE TITLE
React should be opt-in or opt-out

### ISSUE THREAD

**Issue by ematipico** [mobxjs/mst-gql#15]
I think the generation of the code related to React should be an opt-in feature. Store management should be agnostic. 

Or at least, it should be possible to give an **option to not output React code**.

**Comment by FredyC** [comment]
You are not forced to use React related code, but I do agree it could be living in a separate package.

**Comment by ematipico** [comment]
Yes you are right, that's why it's better to pass an option to not generate it instead of delete it every time. 

I'm working on a project that uses MST and GraphQL but not react. It would be handy.

**Comment by FredyC** [comment]
Well, considering the #1 you are kinda free to contribute such change :) I don't think it's going to happen soon otherwise.

**Comment by mweststrate** [comment]
There is --modelsOnly that omits the react and graphqlclient / query stuff. PR for additional flag with in between mode (yes queries, no react) is welcome

**Comment by ematipico** [comment]
Yes I read about `--modelsOnly`, I didn't get that it also omits react stuff. I'll what I can do, if this change is welcome :D

**Comment by mweststrate** [comment]
PR welcome! --noReact?

**Comment by FredyC** [comment]
Seems like it should be another way around :) Instead of disabling stuff, the user should specify what to generate.

Alternatively, it would be nice to adopt the way `graphql-code-generator` allows to [configure plugins](https://graphql-code-generator.com/docs/getting-started/codegen-config) used for generating code. Ultimately, everything should be like a plugin so it's easy to create custom ones.

**Comment by mweststrate** [comment]
Released as 0.1.2. Thanks @ematipico & @dpnolte !
