### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by iho** [mobxjs/mst-gql#175]
Hi
Does it support file upload? Can you give me example?

**Comment by antondomratchev** [comment]
@iho Since mst-gql is simply a type wrapper for schema on the front-end file uploads are out of scope. Here is an article that describes your options in graphql https://leapgraph.com/graphql-file-uploads.

I recommend going with a separate REST endpoint to handle file uploads, unless you are implementing apollo-server in which case the article suggests using apollo-upload-server.
