### ISSUE TITLE
Installation using NPM fails

### ISSUE THREAD

**Issue by jonlambert** [mobxjs/mst-gql#208]
I followed the instructions for installing `mst-gql`, but replacing `yarn` with `npm`. Attempting to run the generator produces the following error:

```
$ npx mst-gql --format ts http://localhost:8200/graphql

mst-gql-scaffold.js --format=ts --outDir=/Users/jon/Code/mst-gql-test/src/models http://localhost:8200/graphql
/bin/sh: /Users/jon/Code/mst-gql-test/node_modules/mst-gql/generator/../node_modules/.bin/apollo: No such file or directory
Command failed: /Users/jon/Code/mst-gql-test/node_modules/mst-gql/generator/../node_modules/.bin/apollo schema:download --endpoint=http://localhost:8200/graphql tmp_schema.json
/bin/sh: /Users/jon/Code/mst-gql-test/node_modules/mst-gql/generator/../node_modules/.bin/apollo: No such file or directory
```

No .bin directory is present within the library:

```
$ ls -la node_modules/mst-gql

drwxr-xr-x    8 jon  staff    256 13 Apr 14:02 .
drwxr-xr-x  641 jon  staff  20512 13 Apr 14:02 ..
-rw-r--r--    1 jon  staff   5321  9 Apr 18:10 CHANGELOG.md
-rw-r--r--    1 jon  staff   1061  9 Oct  2019 LICENSE
-rw-r--r--    1 jon  staff  41046  9 Apr 16:55 README.md
drwxr-xr-x   20 jon  staff    640 13 Apr 14:01 dist
drwxr-xr-x    5 jon  staff    160 13 Apr 14:01 generator
-rw-r--r--    1 jon  staff   3251 13 Apr 14:02 package.json
```

However if I then run the same installation steps with yarn, it works correctly:

```
$ yarn add mst-gql graphql-request
$ yarn mst-gql --format ts http://localhost:8200/graphql

mst-gql-scaffold.js --format=ts --outDir=/Users/jon/Code/mst-gql-test/src/models http://localhost:8200/graphql
...
```

**Comment by chrisdrackett** [comment]
hm, is apollo in your node_modules when using NPM? it's in our dependencies at 2.25.0. The .bin directory is a npm thing and should also be located in `node_modules`

**Comment by chrisdrackett** [comment]
@jonlambert any updates on this?

**Comment by jvcmanke** [comment]
@chrisdrackett I was having the same issue.

I did some investigation to try and fix it and it seems to be a difference between the way npm and yarn save package dependencies in node_modules.

The problem is in:
https://github.com/mobxjs/mst-gql/blob/cf206d4003c43a2a7a1f74411ba121360e6c3c75/generator/mst-gql-scaffold.js#L72

The issue is that when installed with yarn the there is a `.bin` folder both in the main `node_modules` folder and in the one inside the `node_modules/mst-gql/node_modules` folder, when installed with npm only the in the outermost folder exists.

To make it work in both scenarios the line should read:

```javascript
const command = `${__dirname}/../../.bin/apollo client:download-schema --endpoint=${input} ${tmpFile} ${ 
``` 

I'll create a pull request 👍
