### ISSUE TITLE
How to pass variables to fields?

### ISSUE THREAD

**Issue by dodas** [mobxjs/mst-gql#272]
Considering following GraphQL query, how can I query the same with mst-gql's autogenerated root queries?
```graphql
{
  user {
    project(name:"MobX") {
      name
    }
  }
}
```

```ts
rootStore.queryUser({}, user => user
  // How can I pass the `name` variable here?
  .project(project => project.name)
);
```
Thanks!

**Comment by special-character** [comment]
@dodas Would you mind sharing the generated action in `RootStore.base.ts` for `queryUser`? I haven't used mst-gql to query for a nested relation that takes it's own param yet and I am curious if it is supported.

**Comment by dodas** [comment]
Hey @special-character 
This is the relevant action from RootStore.base.ts:
```ts
{
  queryUser(variables?: {  }, resultSelector: string | ((qb: UserModelSelector) => UserModelSelector) = userModelPrimitives.toString(), options: QueryOptions = {}) {
    return self.query<{ user: UserModelType}>(`query user { user {
      ${typeof resultSelector === "function" ? resultSelector(new UserModelSelector()).toString() : resultSelector}
    } }`, variables, options)
  },
}
```
I guess the `query user { user {` on line 3 answers our queston: not possible.

**Comment by special-character** [comment]
@dodas Yeah, I don't think it is possible right now either. I added a test field in my own code base with the same result. I think this would be a good feature request because it seems like a fairly common/powerful GQL paradigm.

**Comment by special-character** [comment]
> I really don't see myself building the fragment myself, dropping out properly typed result.

The result type should still be valid because of the typing on the `query<{user: UserModelType}>`. The fragment builder is somewhat of a helper and I have build my own fragments before to be able to do more dynamic things.

I guess the typing for the generation is lost so it is possible you add a field that isn't supported, but those are pretty obvious when they happen. Definitely not as nice but could get something working for you until they are supported.

**Comment by dodas** [comment]
How could typescript infer the fields I picked in subselection of project() {} if I use string instead of the fragment builder?

**Comment by special-character** [comment]
TS wouldn't be able to infer those fields since the builder doesn't support it yet (like you suggested). In your comment above I thought you were talking about the result of the function call which doesn't rely on the string passed in for the fragment.

It isn't ideal that the fragment builder doesn't have the TS or generation for this yet but I was just saying you can still opt out of the fragment builder if it doesn't support your needs at the moment.

**Comment by nicolasburtey** [comment]
Variables in nested field would also be useful for me. Have to manually write a lot of queries which removes most of the benefits of mst-gql

**Comment by nfour** [comment]
This is the first issue I've run into that had me searching the source code for answers FYI. Will keep track of this thread for updates now.
