### ISSUE TITLE
This package should have a cooler name!

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mst-gql#7]

**Comment by antondomratchev** [comment]
I guess I'll throw a couple in the hat:
Graphix (GraphQL + Mobix State Tree)
Mobix Tree Graph
MST Graph

I think Mobix State Tree is a hard one to work with on its own 😜

**Comment by elie222** [comment]
Graphix is nice and short.

MobX Graph
MobX GraphQL

Some other options that make it clear from the name what they do.

**Comment by odjhey** [comment]
MSTix

**Comment by maxpou** [comment]
For your information, MST is the French acronym for STD (sexually transmitted disease) 😉

**Comment by mwarger** [comment]
Forest

**Comment by gaui** [comment]
MST Graph or just MSG; MobX State Graph 🤪

**Comment by flybayer** [comment]
Honestly I’m not sure there’s anything better than mst-gql unless you choose a normal noun that doesn’t try to mix Mobx, MST or GraphQL :)

**Comment by chrisdrackett** [comment]
agree, if we want a descriptive name we are pretty good right now, IMO.

**Comment by mweststrate** [comment]
Also see replies to this thread, some cool replies in there :)
https://twitter.com/elie2222/status/1155247614654328834

**Comment by aleclarson** [comment]
You can have ["misty"](https://www.npmjs.com/package/misty) if you want. ;) Or maybe "mstical" would work.

**Comment by RXminuS** [comment]
Why not just mstQL? 
![mstql](https://user-images.githubusercontent.com/3949285/64553808-62c2ac80-d33a-11e9-9583-836ee6fd66ba.png)

**Comment by elie222** [comment]
Pronounced Mystical? Cool logo :)

**Comment by stfnsr** [comment]
![Frame 2](https://user-images.githubusercontent.com/4975791/73054245-38593200-3e8a-11ea-9f8e-d3beaf69628a.png)

Basically the MST Logo, but graphql flavored/colored, with a single point in the middle - because mst-gql helps you integrate a gql endpoint into MST  :)

I filled out the lower right bit of the MST Logo just for visual balance first, but thinking about it, giving it a fill kinda makes sense for a scaffolding tool, as it doesn't make you start empty.

**Comment by stfnsr** [comment]
Thinking about it btw,
in case you (@mweststrate ) should be thinking about alternative names for mst,
I would seriously consider "grove" (or "hain", if up for some German ^^).
If I'm not mistaken mst works by composing (sub-)trees, and a grove is just that — a composition of trees.
And generally positively associated, organic/living and resilient. And approachable, compared to e.g a forest (which might sound intimidating through it's sheer size).

(I hope this doesn't come off as presumptuous — I love mst no matter how it's called, but just wanted to throw this out here because I liked the analogy :))

**Comment by antondomratchev** [comment]
Oh man is it time for a poll? mstQL vs mobx-graph-tree

**Comment by fullofcaffeine** [comment]
mstql FTW :)

**Comment by stfnsr** [comment]
What about mst-graphgen?
It's descriptive in what it does I think, generating code based ob a graphql endpoint.

Mst-gql is unclear on whether it uses or generates graphql.

I like mstQL from it's sound "mysticai?", Bit am not fond of the QL at the end, as it makes it sound like a new query language

**Comment by stfnsr** [comment]
(that said, I still favor mobx-graph-tree, not at least bc I spend 10 min on the Logo XD)

**Comment by hexrcs** [comment]
The GraphQL client [urql](https://formidable.com/open-source/urql/) stands for "Universal React Query Library". For me I think it's OK to have QL at the end :P

Love the idea `mstql` aka "Mystical"! <3

To blend the great ideas of @stfnsr and @RXminuS together, I made something like this below.

![mstql@1x](https://user-images.githubusercontent.com/26751752/77739291-89fc7500-7011-11ea-9ea1-7af4c4cf922f.png)

(The font is Rubik, the same as in the GraphQL logo. Not sure if MST uses a specific font)

**Comment by special-character** [comment]
@hexrcs I really like `mstql`. Has meaning but is also easy to say "Mystical" and understand what it means.

**Comment by stfnsr** [comment]
@hexrcs 
Seems like a good synthesis! :)
I have a tendency to overthink the symbolism of things, and yours composes both logos in a more obvious and thus recognizable way.
And it's pink, so that's nice 🎉

**Comment by jesse-savary** [comment]
@hexrcs am I okay to use this logo in any capacity? working on going through older issues

**Comment by hexrcs** [comment]
@jesse-savary Yes, feel free to use it! :)

**Comment by jesse-savary** [comment]
@hexrcs great, thank you

**Comment by DonnyVerduijn** [comment]
Just chiming in here. After learning about mst-gql, i felt it was more like a scaffolding tool for mst (which currently only provides graphql integration). What are the opinions of you guys on this matter and would a rename to scaffold-mst be appropriate?
